<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE configuration
[
<!ELEMENT configuration (properties?, settings?, typeAliases?, typeHandlers?, objectFactory?, plugins?, environments?, mappers?)>

<!ELEMENT properties (property*)>
<!ATTLIST properties resource CDATA #IMPLIED url CDATA #IMPLIED>

<!ELEMENT property EMPTY>
<!ATTLIST property name CDATA #REQUIRED value CDATA #REQUIRED>

<!ELEMENT settings (setting+)>

<!ELEMENT setting EMPTY>
<!ATTLIST setting name CDATA #REQUIRED value CDATA #REQUIRED>

<!ELEMENT typeAliases (typeAlias+)>

<!ELEMENT typeAlias EMPTY>
<!ATTLIST typeAlias type CDATA #REQUIRED alias CDATA #IMPLIED>

<!ELEMENT typeHandlers (typeHandler+)>

<!ELEMENT typeHandler EMPTY>
<!ATTLIST typeHandler javaType CDATA #REQUIRED jdbcType CDATA #IMPLIED handler CDATA #REQUIRED>

<!ELEMENT objectFactory (property*)>
<!ATTLIST objectFactory type CDATA #REQUIRED>

<!ELEMENT plugins (plugin+)>

<!ELEMENT plugin (property*)>
<!ATTLIST plugin interceptor CDATA #REQUIRED>

<!ELEMENT environments (environment+)>
<!ATTLIST environments default CDATA #REQUIRED>

<!ELEMENT environment (transactionManager,dataSource)>
<!ATTLIST environment id CDATA #REQUIRED>

<!ELEMENT transactionManager (property*)>
<!ATTLIST transactionManager type CDATA #REQUIRED>

<!ELEMENT dataSource (property*)>
<!ATTLIST dataSource type CDATA #REQUIRED>

<!ELEMENT mappers (mapper+)>

<!ELEMENT mapper EMPTY>
<!ATTLIST mapper resource CDATA #IMPLIED url CDATA #IMPLIED>
]>

<!--
    Copyright 2010 The myBatis Team
    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at
		http://www.apache.org/licenses/LICENSE-2.0
    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,\
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
		See the License for the specific language governing permissions and
    limitations under the License.

-->

<configuration>
  <settings>
    <setting name="localCacheScope" value="STATEMENT"/>
  </settings>
  
  <typeAliases>
    <typeAlias type="com.brookmonte.friday.FridayPolymer.domain.calendar.FridayCalendar" alias="FridayCalendar"/>
    <typeAlias type="com.brookmonte.friday.FridayPolymer.domain.admin.Permission" alias="Permission"/>
    <typeAlias type="com.brookmonte.friday.FridayPolymer.domain.user.FridayUser" alias="FridayUser"/>
    <typeAlias type="com.brookmonte.friday.FridayPolymer.domain.location.FridayLocation" alias="FridayLocation"/>
    <typeAlias type="com.brookmonte.friday.FridayPolymer.domain.location.FridayCountry" alias="FridayCountry"/>    
    <typeAlias type="com.brookmonte.friday.FridayPolymer.domain.user.FridayEmailDefinition" alias="FridayEmailDefinition"/>
    <typeAlias type="com.brookmonte.friday.FridayPolymer.domain.user.FridayPhoneDefinition" alias="FridayPhoneDefinition"/>
    <typeAlias type="com.brookmonte.friday.FridayPolymer.domain.calendar.FridayHoliday" alias="FridayHoliday"/>
    <typeAlias type="com.brookmonte.friday.FridayPolymer.domain.calendar.FridayEventDescription" alias="FridayEventDescription"/>
    <typeAlias type="com.brookmonte.friday.FridayPolymer.domain.calendar.FridayEventInstance" alias="FridayEventInstance"/>
    <typeAlias type="com.brookmonte.friday.FridayPolymer.domain.calendar.FridayEventTypeEntry" alias="FridayEventTypeEntry"/>
    <typeAlias type="com.brookmonte.friday.FridayPolymer.domain.admin.UserPreference" alias="UserPreference"/>
    <typeAlias type="com.brookmonte.friday.FridayPolymer.domain.contact.FridayUserContact" alias="FridayUserContact"/>
	<typeAlias type="com.brookmonte.friday.FridayPolymer.domain.contact.FridayUserContactDetails" alias="FridayUserContactDetails"/>
	<typeAlias type="com.brookmonte.friday.FridayPolymer.domain.contact.FridayContactKeyType" alias="FridayContactKeyType"/>
	<typeAlias type="com.brookmonte.friday.FridayPolymer.domain.task.FridayTask" alias="FridayTask"/>
	<typeAlias type="com.brookmonte.friday.FridayPolymer.domain.task.FridayTaskInstance" alias="FridayTaskInstance"/>
  </typeAliases>
  
  <typeHandlers>
    <typeHandler handler="com.brookmonte.friday.FridayPolymer.domain.fridayUtils.DateTimeTypeHandler" javaType="org.joda.time.DateTime" />
  </typeHandlers>  
  
  <mappers>
    <mapper resource="com/brookmonte/friday/maps/Application.xml"/>
    <mapper resource="com/brookmonte/friday/maps/User.xml"/>
    <mapper resource="com/brookmonte/friday/maps/Location.xml"/>
    <mapper resource="com/brookmonte/friday/maps/Calendar.xml"/>
    <mapper resource="com/brookmonte/friday/maps/Contact.xml"/>
    <mapper resource="com/brookmonte/friday/maps/Task.xml"/>
  </mappers>
</configuration>
